# 🏠 Society Maintenance Agent — Interactive Test Notebook
Use this notebook to test the agent interactively cell by cell.

## ⚙️ Cell 1 — Setup (Run this first every time)

In [1]:
import sys, os

# Point Python to the project root so all imports work
PROJECT_ROOT = os.path.abspath('.')  # assumes notebook is in society-agent/
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from dotenv import load_dotenv
load_dotenv('.env')  # load GROQ_API_KEY

print('GROQ_API_KEY set:', bool(os.getenv('GROQ_API_KEY')))
print('Setup done ✅')

GROQ_API_KEY set: True
Setup done ✅

## 📊 Cell 2 — Test Data Loader directly

In [2]:
from server.data_loader import (
    get_all_months,
    get_pending_maintenance,
    get_expense_summary,
    get_balance_sheet,
    get_flat_history,
)

# All months available
months = get_all_months()
print('Available months:', months)

Available months: ['Jan_2024', 'Feb_2024', 'March_2024', 'April_2024', 'May_2024', 'June_2024', 'July_2024', 'Aug_2024', 'Sep_2024', 'Oct_2024', 'Nov_2024', 'Dec_2024', 'Jan_2025', 'Feb_2025', 'March_2025', 'April_2025', 'May_2025', 'June_2025', 'July_2025', 'Aug_2025', 'Sep_2025', 'Oct_2025', 'Nov_2025', 'Dec_2025']

In [3]:
# Pending maintenance for a specific month
pending = get_pending_maintenance(month='Jan_2024')
print(f'Pending count: {len(pending)}')
pending

Pending count: 1

      month  flat_number    name  amount_due  late_charges
0  Jan_2024          805  refuse         0.0           0.0

In [4]:
# Expense summary for a year
expenses = get_expense_summary(year=2024)
expenses

      expense_type  total_amount  transaction_count
2      Electricity        329630                 11
1         Cleaning        169100                 13
4            Other        134375                 84
0  A1,A2,A3 Common         21996                  9
3       Name Board         20000                  1
5   Security Guard          5550                  1
7       Water Bill          1050                  2
6       Stationary           100                  1

In [5]:
# Balance sheet for a month
bs = get_balance_sheet(month='Jan_2024')
print(f"Period         : {bs['period']}")
print(f"Total Collected: Rs. {bs['total_collected']:,.0f}")
print(f"Total Expenses : Rs. {bs['total_expenses']:,.0f}")
print(f"Net Balance    : Rs. {bs['net_balance']:,.0f}")
print()
print('Expense Breakdown:')
for item in bs['expense_breakdown']:
    print(f"  {item['expense_type']:<25} Rs. {item['total']:,.0f}")

Period         : Jan_2024
Total Collected: Rs. 76,000
Total Expenses : Rs. 56,626
Net Balance    : Rs. 19,374

Expense Breakdown:
  Electricity               Rs. 30,840
  Other                     Rs. 14,097
  Cleaning                  Rs. 11,000
  Water Bill                Rs. 689

In [6]:
# Flat payment history
history = get_flat_history(601)
history[['month', 'date', 'amount', 'is_paid']]

         month       date  amount  is_paid
0   April_2024 2024-05-12  1000.0     True
1     Aug_2024 2024-09-20  1000.0     True
2     Dec_2024 2025-01-15  1000.0     True
3     Feb_2024 2024-03-19  1000.0     True
4     Jan_2024 2024-02-04  1000.0     True
5    July_2024 2024-08-20  1000.0     True
6    June_2024 2024-07-20  1000.0     True
7   March_2024 2024-04-30  1000.0     True
8     May_2024 2024-06-20  1000.0     True
9     Nov_2024 2024-12-20  1000.0     True
10    Oct_2024 2024-11-11  1000.0     True
11    Sep_2024 2024-10-14  1000.0     True
12  April_2025 2025-05-20  1000.0     True
13    Aug_2025 2025-09-20  1000.0     True
14    Dec_2025        NaT     0.0    False
15    Feb_2025 2025-03-20  1000.0     True
16    Jan_2025 2025-02-20  1000.0     True
17   July_2025        NaT  1000.0     True
18   June_2025 2025-07-19  1000.0     True
19  March_2025 2025-04-20  1000.0     True
20    May_2025 2025-06-20  1000.0     True
21    Nov_2025 2025-12-19  1000.0     True
22    Oct_2025 2025-11-20  1000.0     True
23    Sep_2025        NaT  1000.0     True

## 🤖 Cell 3 — Build the Agent

In [1]:
from agent.graph import get_graph, chat

# Build the graph (only once)
graph = get_graph()
print('Agent graph built ✅')
print('Nodes:', list(graph.get_graph().nodes.keys()))

c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\langgraph\cache\base\__init__.py:8: LangChainPendingDeprecationWarning: The default value of `allowed_objects` will change in a future version. Pass an explicit value (e.g., allowed_objects='messages' or allowed_objects='core') to suppress this warning.
  from langgraph.checkpoint.serde.jsonplus import JsonPlusSerializer

Agent graph built ✅
Nodes: ['__start__', 'llm_node', 'tool_node', '__end__']

## 💬 Cell 4 — Chat with the Agent
Change the question below and re-run the cell to ask anything.

In [2]:
# ✏️ Change this question and run the cell
question = "Hello! What can you help me with?"

response = chat(question, thread_id='notebook-session')
print(response)

[07/14/26 14:39:44] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=15150302;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=15150303;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

I can assist you with various tasks related to society maintenance, such as checking pending maintenance, balance sheets, expense summaries, flat histories, and more. What would you like to know or accomplish today?

In [3]:
question = "What months of data do we have?"
response = chat(question, thread_id='notebook-session')
print(response)

[07/14/26 14:40:04] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=15150308;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=15150309;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

[07/14/26 14:40:05] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=15150314;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=15150315;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

**Available months:**
- **2024:** January, February, March, April, May, June, July, August, September, October, November, December
- **2025:** January, February, March, April, May, June, July, August, September, October, November, December

In [4]:
question = "How many flats did not pay in January 2024?"
response = chat(question, thread_id='notebook-session')
print(response)

[07/14/26 14:40:17] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=15150320;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=15150321;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

[07/14/26 14:40:18] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=15150326;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=15150327;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 429 Too Many Requests"

                    INFO     Retrying request to /openai/v1/chat/completions in 22.000000      ]8;id=15150334;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\groq\_base_client.py\_base_client.py]8;;\:]8;id=15150335;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\groq\_base_client.py#1068\1068]8;;\
                             seconds

[07/14/26 14:40:40] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=15150340;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=15150341;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

**1 flat** have not paid maintenance for **January 2024:**
- Flat 805 — refuse

In [5]:
question = "give me the report for pending for the year 2024"
response = chat(question, thread_id='notebook-session')
print(response)

[07/14/26 14:43:56] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=15150346;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=15150347;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

[07/14/26 14:43:57] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=15150352;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=15150353;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

**8 flats** have outstanding maintenance dues for **2024:**

| Flat | Resident | Months Unpaid | Months | Total Due |
|------|----------|---------------|--------|-----------|
| 202  | Vitthal Udhavrao Kausale | 1 | Dec_2024 | Rs. 1,000 |
| 207  | Harshal Bhalerao | 10 | March_2024, April_2024, May_2024, June_2024, July_2024, Aug_2024, Sep_2024, Oct_2024, Nov_2024, Dec_2024 | Rs. 10,000 |
| 302  | Bharat Danave | 10 | March_2024, April_2024, May_2024, June_2024, July_2024, Aug_2024, Sep_2024, Oct_2024, Nov_2024, Dec_2024 | Rs. 10,000 |
| 602  | pradeep chindaliya | 3 | Oct_2024, Nov_2024, Dec_2024 | Rs. 3,000 |
| 608  | Mahesh Katkar | 3 | March_2024, April_2024, May_2024 | Rs. 3,000 |
| 805  | refuse | 12 | Jan_2024, Feb_2024, March_2024, April_2024, May_2024, June_2024, July_2024, Aug_2024, Sep_2024, Oct_2024, Nov_2024, Dec_2024 | Rs. 12,000 |
| 904  | Pratibha Kapate | 10 | March_2024, April_2024, May_2024, June_2024, July_2024, Aug_2024, Sep_2024, Oct_2024, Nov_2024, Dec_2024 | Rs. 10,000 |
| 908  | Rohini Lakhole | 10 | March_2024, April_2024, May_2024, June_2024, July_2024, Aug_2024, Sep_2024, Oct_2024, Nov_2024, Dec_2024 | Rs. 10,000 |

**Total outstanding: Rs. 59,000**

In [ ]:
question = "What was the total electricity expense in 2024?"
response = chat(question, thread_id='notebook-session')
print(response)

In [ ]:
question = "Show me payment history for flat 601"
response = chat(question, thread_id='notebook-session')
print(response)

## 🔄 Cell 5 — Free-form Chat (loop)
Run this cell to have a back-and-forth conversation in the notebook output.

In [9]:
# List of questions to ask in sequence (simulates a conversation)
questions = [
    "Which flats have not paid for March 2025?",
    "What about April 2025?",           # tests memory (no month context needed)
    "Who is the resident of flat 305?",
    "How much did they pay in total?",   # tests memory (refers to flat 305)
]

session_id = 'loop-session'
for q in questions:
    print(f'\n👤 You : {q}')
    ans = chat(q, thread_id=session_id)
    print(f'🤖 Bot : {ans}')
    print('-' * 50)

👤 You : Which flats have not paid for March 2025?

[07/08/26 15:51:47] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=3757940;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=3757941;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

[07/08/26 15:51:49] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=3757946;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=3757947;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

🤖 Bot : The following flats have not paid for March 2025:

1. Flat 101 - Bhau Maruti Jadhav
2. Flat 202 - Vitthal Udhavrao Kausale
3. Flat 207 - Harshal Bhalerao
4. Flat 302 - Bharat Danave
5. Flat 602 - Pradeep Chindaliya
6. Flat 805 - Refuse
7. Flat 904 - Pratibha Kapate
8. Flat 908 - Rohini Lakhole
9. Flat 1101 - Vishal Shantaram Sonawane

All of these flats have an amount due of Rs. 0.0 and late charges of Rs. 0.0.
--------------------------------------------------

👤 You : What about April 2025?

[07/08/26 15:51:50] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=3757952;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=3757953;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

[07/08/26 15:51:51] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=3757958;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=3757959;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

🤖 Bot : The following flats have not paid for April 2025:

1. Flat 101 - Bhau Maruti Jadhav
2. Flat 202 - Vitthal Udhavrao Kausale
3. Flat 207 - Harshal Bhalerao
4. Flat 302 - Bharat Danave
5. Flat 602 - Pradeep Chindaliya
6. Flat 805 - Refuse
7. Flat 904 - Pratibha Kapate
8. Flat 908 - Rohini Lakhole
9. Flat 1101 - Vishal Shantaram Sonawane
10. Flat 1102 - Avinash Arun Jagtap

All of these flats have an amount due of Rs. 0.0 and late charges of Rs. 0.0.
--------------------------------------------------

👤 You : Who is the resident of flat 305?

[07/08/26 15:51:53] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=3757964;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=3757965;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

[07/08/26 15:51:54] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=3757970;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=3757971;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 429 Too Many Requests"

                    INFO     Retrying request to /openai/v1/chat/completions in 15.000000      ]8;id=3757978;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\groq\_base_client.py\_base_client.py]8;;\:]8;id=3757979;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\groq\_base_client.py#1068\1068]8;;\
                             seconds

[07/08/26 15:52:10] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=3757984;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=3757985;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

🤖 Bot : The resident of flat 305 is Shashikant Ijare.
--------------------------------------------------

👤 You : How much did they pay in total?

[07/08/26 15:52:11] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=3757990;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=3757991;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 429 Too Many Requests"

                    INFO     Retrying request to /openai/v1/chat/completions in 21.000000      ]8;id=3757996;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\groq\_base_client.py\_base_client.py]8;;\:]8;id=3757997;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\groq\_base_client.py#1068\1068]8;;\
                             seconds

[07/08/26 15:52:33] INFO     HTTP Request: POST https://api.groq.com/openai/v1/chat/completions     ]8;id=3758002;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py\_client.py]8;;\:]8;id=3758003;file://c:\Users\VilasTade\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py#1025\1025]8;;\
                             "HTTP/1.1 200 OK"

🤖 Bot : Shashikant Ijare, the resident of flat 305, paid a total of Rs. 23,000.
--------------------------------------------------

## 🔁 Cell 6 — Start a fresh conversation (reset memory)

In [ ]:
import time

# Use a unique thread_id to start a brand new conversation with no history
new_session = f'fresh-{int(time.time())}'
print(f'New session ID: {new_session}')

response = chat("What is the net balance for 2025?", thread_id=new_session)
print(response)

In [1]:
from server import data_loader as dl

In [3]:
dl._normalise_month('Jun_2025')

'June_2025'

In [4]:
df = dl.load_maintenance()

In [23]:
df

,month,date,flat_number,name,amount,late_charges,is_vacant,is_paid,year
0,Jan_2024,2024-05-13,101,Bhau Maruti Jadhav,1000.0,0.0,False,True,2024
1,Jan_2024,2024-02-07,102,Pranay Pandurang Karle,1000.0,0.0,False,True,2024
2,Jan_2024,NaT,103,NA,0.0,0.0,True,False,2024
3,Jan_2024,2024-03-05,104,Sakshi Baburao Kottalagi,1000.0,0.0,False,True,2024
4,Jan_2024,2024-05-12,105,Prasad Ghangale,1000.0,0.0,False,True,2024
...,...,...,...,...,...,...,...,...,...
2107,Dec_2025,NaT,1104,Nishikant Joshi,0.0,0.0,False,False,2025
2108,Dec_2025,NaT,1105,Anita Kanhaiya Singh,0.0,0.0,False,False,2025
2109,Dec_2025,NaT,1106,Pramod Rajaram Deshmane,0.0,0.0,False,False,2025
2110,Dec_2025,NaT,1107,shobhabai rajendra patil,0.0,0.0,False,False,2025
2111,Dec_2025,NaT,1108,Rahul Sandip Savaiajkar,0.0,0.0,False,False,2025

             month  date  name  amount  late_charges  is_vacant  is_paid  year
flat_number
101             12     0    12      12            12         12       12    12
102              1     0     1       1             1          1        1     1
103              2     0     2       2             2          2        2     2
104              2     0     2       2             2          2        2     2
105              1     0     1       1             1          1        1     1
...            ...   ...   ...     ...           ...        ...      ...   ...
1104             2     0     2       2             2          2        2     2
1105             1     0     1       1             1          1        1     1
1106             4     1     4       4             4          4        4     4
1107             6     1     6       6             6          6        6     6
1108             4     1     4       4             4          4        4     4

[85 rows x 8 columns]